project:
  type: website
  output-dir: docs
  
website:
  title: "Community Contributions 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/jtr13/cc24mw
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, EDAV 2024"

format:
  html:
    theme: cerulean
    toc: true

editor: source

